language: java

jdk:
  - openjdk7
  - oraclejdk7

env:
  global:
    - SONATYPE_USERNAME=ingwar
    - secure: "Lqi30fOkp2QgSTxLDWlPW1ArSva/mWHW5yjTalw1Pk/v7LTEHA4LfcOEMKJ/RfH3gKvpq0UP90Nb8t4cAooM1AkHKLb/5lOv8eys4Qj3XyeJcmDLJz8Znre0r6SWA8/DFMzugjPu++4ul+CQOFB8/DkCeA3hDVRuI4yHYKVwArM="
  matrix:
    - PROFILE=test-glassfish-embeded
    - PROFILE=test-jboss-managed,coveralls-coverage
    
script: mvn install -P${PROFILE}

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { python travis/addServer.py; mvn clean deploy -DskipTests --settings ~/.m2/mySettings.xml; };"

