language: java

jdk:
  - openjdk7
  - oraclejdk7

env:
  global:
    - SONATYPE_USERNAME=ingwar
    - secure: ""
  matrix:
    - PROFILE=test-glassfish-embeded
    
script: mvn clean install -P${PROFILE}

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { python travis/addServer.py; mvn clean deploy -DskipTests --settings ~/.m2/mySettings.xml; };"

