language: java

sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - DEPLOY_USERNAME=ingwarsw
  matrix:
    - PROFILE=test-jboss-managed
    - PROFILE=test-jboss-managed-domain
    - PROFILE=test-wildfly-managed
    - PROFILE=test-wildfly-managed-domain
    - PROFILE=test-glassfish-embeded

matrix:
    allow_failures:
        - env: "PROFILE=test-jboss-managed"
        - env: "PROFILE=test-glassfish-embeded"
    include:
        - jdk: oraclejdk8
          env: "PROFILE=test-wildfly-managed,coveralls-coverage"

install: travis/travis.py --fetch

script: travis/travis.py --test

deploy:
  - provider: script
    script: travis/travis.py --deploy
    on:
      tags: true

